
// Copyright 2012 Google Inc. All rights reserved.
(function(){

var data = {
"resource": {
  "version":"1",
  "macros":[],
  "tags":[],
  "predicates":[],
  "rules":[]
},
"runtime":[
[],[]
]};

var aa=function(a,b){function c(){}c.prototype=b.prototype;a.ce=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Rd=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};var g=function(a,b){this.o=a;this.Ec=b};g.prototype.Rc=function(){return this.o};g.prototype.getType=g.prototype.Rc;g.prototype.getData=function(){return this.Ec};g.prototype.getData=g.prototype.getData;var ba=function(a){return"number"===typeof a&&0<=a&&isFinite(a)&&0===a%1||"string"===typeof a&&"-"!==a[0]&&a===""+parseInt(a,10)},ca=function(){this.V={};this.Ea=!1};ca.prototype.get=function(a){return this.V["dust."+a]};ca.prototype.set=function(a,b){!this.Ea&&(this.V["dust."+a]=b)};ca.prototype.has=function(a){return this.V.hasOwnProperty("dust."+a)};var da=function(a){var b=[],c;for(c in a.V)a.V.hasOwnProperty(c)&&b.push(c.substr(5));return b};
ca.prototype.remove=function(a){!this.Ea&&delete this.V["dust."+a]};var t=function(a){this.Y=new ca;this.h=[];a=a||[];for(var b in a)a.hasOwnProperty(b)&&(ba(b)?this.h[Number(b)]=a[Number(b)]:this.Y.set(b,a[b]))};t.prototype.toString=function(){for(var a=[],b=0;b<this.h.length;b++){var c=this.h[b];null===c||void 0===c?a.push(""):a.push(c.toString())}return a.join(",")};t.prototype.set=function(a,b){if("length"==a){if(!ba(b))throw"RangeError: Length property must be a valid integer.";this.h.length=Number(b)}else ba(a)?this.h[Number(a)]=b:this.Y.set(a,b)};
t.prototype.set=t.prototype.set;t.prototype.get=function(a){return"length"==a?this.length():ba(a)?this.h[Number(a)]:this.Y.get(a)};t.prototype.get=t.prototype.get;t.prototype.length=function(){return this.h.length};t.prototype.H=function(){for(var a=da(this.Y),b=0;b<this.h.length;b++)a.push(b+"");return new t(a)};t.prototype.getKeys=t.prototype.H;t.prototype.remove=function(a){ba(a)?delete this.h[Number(a)]:this.Y.remove(a)};t.prototype.remove=t.prototype.remove;t.prototype.pop=function(){return this.h.pop()};
t.prototype.pop=t.prototype.pop;t.prototype.push=function(a){return this.h.push.apply(this.h,Array.prototype.slice.call(arguments))};t.prototype.push=t.prototype.push;t.prototype.shift=function(){return this.h.shift()};t.prototype.shift=t.prototype.shift;t.prototype.splice=function(a,b,c){return new t(this.h.splice.apply(this.h,arguments))};t.prototype.splice=t.prototype.splice;t.prototype.unshift=function(a){return this.h.unshift.apply(this.h,Array.prototype.slice.call(arguments))};
t.prototype.unshift=t.prototype.unshift;t.prototype.has=function(a){return ba(a)&&this.h.hasOwnProperty(a)||this.Y.has(a)};var ea=function(){function a(a,c){if(b[a]){if(b[a].za+c>b[a].max)throw Error("Quota exceeded");b[a].za+=c}}var b={},c=void 0,d=void 0,e={md:function(a){c=a},sb:function(){c&&a(c,1)},nd:function(a){d=a},L:function(b){d&&a(d,b)},Cd:function(a,c){b[a]=b[a]||{za:0};b[a].max=c},Qc:function(a){return b[a]&&b[a].za||0},reset:function(){b={}},zc:a};e.onFnConsume=e.md;e.consumeFn=e.sb;e.onStorageConsume=e.nd;e.consumeStorage=e.L;e.setMax=e.Cd;e.getConsumed=e.Qc;e.reset=e.reset;e.consume=e.zc;return e};var fa=function(a,b){this.N=a;this.M=b;this.h=new ca};fa.prototype.add=function(a,b){this.N.L(("string"===typeof a?a.length:1)+("string"===typeof b?b.length:1));this.h.set(a,b)};fa.prototype.add=fa.prototype.add;fa.prototype.set=function(a,b){this.M&&this.M.has(a)?this.M.set(a,b):(this.N.L(("string"===typeof a?a.length:1)+("string"===typeof b?b.length:1)),this.h.set(a,b))};fa.prototype.set=fa.prototype.set;fa.prototype.get=function(a){return this.h.has(a)?this.h.get(a):this.M?this.M.get(a):void 0};
fa.prototype.get=fa.prototype.get;fa.prototype.has=function(a){return!!this.h.has(a)||!(!this.M||!this.M.has(a))};fa.prototype.has=fa.prototype.has;fa.prototype.I=function(){return this.N};var ha=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},ia=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1};var u=function(a,b){ca.call(this);this.Fb=a;this.Oc=b};aa(u,ca);var ka=function(a,b){for(var c,d=0;d<b.length&&!(c=ja(a,b[d]),c instanceof g);d++);return c},ja=function(a,b){var c=a.get(String(b[0]));if(!(c&&c instanceof u))throw"Attempting to execute non-function "+b[0]+".";return c.i.apply(c,[a].concat(b.slice(1)))};u.prototype.toString=function(){return this.Fb};u.prototype.getName=function(){return this.Fb};u.prototype.getName=u.prototype.getName;u.prototype.H=function(){return new t(da(this))};
u.prototype.getKeys=u.prototype.H;u.prototype.i=function(a,b){a.I().sb();return this.Oc.apply({w:function(){return a},evaluate:function(b){var c=a;return ha(b)?ja(c,b):b},fa:function(b){return ka(a,b)},I:function(){return a.I()}},Array.prototype.slice.call(arguments,1))};u.prototype.invoke=u.prototype.i;var w=function(){ca.call(this)};aa(w,ca);w.prototype.H=function(){return new t(da(this))};w.prototype.getKeys=w.prototype.H;/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var ma=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,na=function(a){if(null==a)return String(a);var b=ma.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},oa=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},pa=function(a){if(!a||"object"!=na(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!oa(a,"constructor")&&!oa(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||oa(a,b)},qa=function(a,b){var c=b||("array"==na(a)?[]:{}),d;for(d in a)if(oa(a,d)){var e=a[d];"array"==na(e)?("array"!=na(c[d])&&(c[d]=[]),c[d]=qa(e,c[d])):pa(e)?(pa(c[d])||(c[d]={}),c[d]=qa(e,c[d])):c[d]=e}return c};var ra=function(a){if(a instanceof t){for(var b=[],c=Number(a.get("length")),d=0;d<c;d++)a.has(d)&&(b[d]=ra(a.get(d)));return b}if(a instanceof w){for(var e={},f=a.H(),h=f.length(),k=0;k<h;k++)e[f.get(k)]=ra(a.get(f.get(k)));return e}return a instanceof u?function(){for(var b=Array.prototype.slice.call(arguments,0),c=0;c<b.length;c++)b[c]=sa(b[c]);var d=new fa(ea());return ra(a.i.apply(a,[d].concat(b)))}:a},sa=function(a){if(ha(a)){for(var b=[],c=0;c<a.length;c++)a.hasOwnProperty(c)&&(b[c]=sa(a[c]));
return new t(b)}if(pa(a)){var d=new w,e;for(e in a)a.hasOwnProperty(e)&&d.set(e,sa(a[e]));return d}if("function"===typeof a)return new u("",function(b){for(var c=Array.prototype.slice.call(arguments,0),d=0;d<c.length;d++)c[d]=ra(this.evaluate(c[d]));return sa(a.apply(a,c))});var f=typeof a;if(null===a||"string"===f||"number"===f||"boolean"===f)return a};var ta={control:function(a,b){return new g(a,this.evaluate(b))},fn:function(a,b,c){var d=this.w(),e=this.evaluate(b);if(!(e instanceof t))throw"Error: non-List value given for Fn argument names.";var f=Array.prototype.slice.call(arguments,2);this.I().L(a.length+f.length);return new u(a,function(){return function(a){for(var b=new fa(d.N,d),c=Array.prototype.slice.call(arguments,0),h=0;h<c.length;h++)if(c[h]=this.evaluate(c[h]),c[h]instanceof g)return c[h];for(var n=e.get("length"),p=0;p<n;p++)p<c.length?
b.set(e.get(p),c[p]):b.set(e.get(p),void 0);b.set("arguments",new t(c));var q=ka(b,f);if(q instanceof g)return"return"===q.o?q.getData():q}}())},list:function(a){var b=this.I();b.L(arguments.length);for(var c=new t,d=0;d<arguments.length;d++){var e=this.evaluate(arguments[d]);"string"===typeof e&&b.L(e.length?e.length-1:0);c.push(e)}return c},map:function(a){for(var b=this.I(),c=new w,d=0;d<arguments.length-1;d+=2){var e=this.evaluate(arguments[d])+"",f=this.evaluate(arguments[d+1]),h=e.length;h+=
"string"===typeof f?f.length:1;b.L(h);c.set(e,f)}return c},undefined:function(){}};var ua=function(){this.N=ea();this.Bb=new fa(this.N)};ua.prototype.K=function(a,b){var c=new u(a,b);c.Ea=!0;this.Bb.set(a,c)};ua.prototype.addInstruction=ua.prototype.K;ua.prototype.rb=function(a,b){ta.hasOwnProperty(a)&&this.K(b||a,ta[a])};ua.prototype.addNativeInstruction=ua.prototype.rb;ua.prototype.I=function(){return this.N};ua.prototype.getQuota=ua.prototype.I;
ua.prototype.C=function(a,b){var c=Array.prototype.slice.call(arguments,0),d=ja(this.Bb,c);if(d instanceof g||d instanceof u||d instanceof t||d instanceof w||null===d||void 0===d||"string"===typeof d||"number"===typeof d||"boolean"===typeof d)return d};ua.prototype.execute=ua.prototype.C;ua.prototype.zd=function(a){for(var b=0;b<arguments.length;b++)this.C.apply(this,arguments[b])};ua.prototype.run=ua.prototype.zd;var va=function(a){for(var b=[],c=Number(a.get("length")),d=0;d<c;d++)a.has(d)&&(b[d]=a.get(d));return b};var y={Fd:"concat every filter forEach hasOwnProperty indexOf join lastIndexOf map pop push reduce reduceRight reverse shift slice some sort splice unshift toString".split(" ")},z=function(a){return Number(a.get("length"))};y.concat=function(a,b){for(var c=[],d=z(this),e=0;e<d;e++)c.push(this.get(e));for(e=1;e<arguments.length;e++)if(arguments[e]instanceof t)for(var f=arguments[e],h=z(f),k=0;k<h;k++)c.push(f.get(k));else c.push(arguments[e]);return new t(c)};
y.every=function(a,b){for(var c=z(this),d=0;d<z(this)&&d<c;d++)if(this.has(d)&&!b.i(a,this.get(d),d,this))return!1;return!0};y.filter=function(a,b){for(var c=z(this),d=[],e=0;e<z(this)&&e<c;e++)this.has(e)&&b.i(a,this.get(e),e,this)&&d.push(this.get(e));return new t(d)};y.forEach=function(a,b){for(var c=z(this),d=0;d<z(this)&&d<c;d++)this.has(d)&&b.i(a,this.get(d),d,this)};y.hasOwnProperty=function(a,b){return this.has(b)};
y.indexOf=function(a,b,c){var d=z(this),e=void 0===c?0:Number(c);0>e&&(e=Math.max(d+e,0));for(var f=e;f<d;f++)if(this.has(f)&&this.get(f)===b)return f;return-1};y.join=function(a,b){for(var c=[],d=z(this),e=0;e<d;e++)c.push(this.get(e));return c.join(b)};y.lastIndexOf=function(a,b,c){var d=z(this),e=d-1;void 0!==c&&(e=0>c?d+c:Math.min(c,e));for(var f=e;0<=f;f--)if(this.has(f)&&this.get(f)===b)return f;return-1};
y.map=function(a,b){for(var c=z(this),d=[],e=0;e<z(this)&&e<c;e++)this.has(e)&&(d[e]=b.i(a,this.get(e),e,this));return new t(d)};y.pop=function(){return this.pop()};y.push=function(a,b){return this.push.apply(this,Array.prototype.slice.call(arguments,1))};
y.reduce=function(a,b,c){var d=z(this),e,f;if(void 0!==c)e=c,f=0;else{if(0==d)throw"TypeError: Reduce on List with no elements.";for(var h=0;h<d;h++)if(this.has(h)){e=this.get(h);f=h+1;break}if(h==d)throw"TypeError: Reduce on List with no elements.";}for(h=f;h<d;h++)this.has(h)&&(e=b.i(a,e,this.get(h),h,this));return e};
y.reduceRight=function(a,b,c){var d=z(this),e,f;if(void 0!==c)e=c,f=d-1;else{if(0==d)throw"TypeError: ReduceRight on List with no elements.";for(var h=1;h<=d;h++)if(this.has(d-h)){e=this.get(d-h);f=d-(h+1);break}if(h>d)throw"TypeError: ReduceRight on List with no elements.";}for(h=f;0<=h;h--)this.has(h)&&(e=b.i(a,e,this.get(h),h,this));return e};y.reverse=function(){for(var a=va(this),b=a.length-1,c=0;0<=b;b--,c++)a.hasOwnProperty(b)?this.set(c,a[b]):this.remove(c);return this};y.shift=function(){return this.shift()};
y.slice=function(a,b,c){var d=z(this);void 0===b&&(b=0);b=0>b?Math.max(d+b,0):Math.min(b,d);c=void 0===c?d:0>c?Math.max(d+c,0):Math.min(c,d);c=Math.max(b,c);for(var e=[],f=b;f<c;f++)e.push(this.get(f));return new t(e)};y.some=function(a,b){for(var c=z(this),d=0;d<z(this)&&d<c;d++)if(this.has(d)&&b.i(a,this.get(d),d,this))return!0;return!1};
y.sort=function(a,b){var c=va(this);void 0===b?c.sort():c.sort(function(c,d){return Number(b.i(a,c,d))});for(var d=0;d<c.length;d++)c.hasOwnProperty(d)?this.set(d,c[d]):this.remove(d)};y.splice=function(a,b,c,d){return this.splice.apply(this,Array.prototype.splice.call(arguments,1,arguments.length-1))};y.toString=function(){return this.toString()};y.unshift=function(a,b){return this.unshift.apply(this,Array.prototype.slice.call(arguments,1))};var B={Db:{ADD:0,AND:1,APPLY:2,ASSIGN:3,BREAK:4,CASE:5,CONTINUE:6,CONTROL:49,CREATE_ARRAY:7,CREATE_OBJECT:8,DEFAULT:9,DEFN:50,DIVIDE:10,DO:11,EQUALS:12,EXPRESSION_LIST:13,FN:51,FOR:14,FOR_IN:47,GET:15,GET_CONTAINER_VARIABLE:48,GET_INDEX:16,GET_PROPERTY:17,GREATER_THAN:18,GREATER_THAN_EQUALS:19,IDENTITY_EQUALS:20,IDENTITY_NOT_EQUALS:21,IF:22,LESS_THAN:23,LESS_THAN_EQUALS:24,MODULUS:25,MULTIPLY:26,NEGATE:27,NOT:28,NOT_EQUALS:29,NULL:45,OR:30,PLUS_EQUALS:31,POST_DECREMENT:32,POST_INCREMENT:33,PRE_DECREMENT:34,
PRE_INCREMENT:35,QUOTE:46,RETURN:36,SET_PROPERTY:43,SUBTRACT:37,SWITCH:38,TERNARY:39,TYPEOF:40,UNDEFINED:44,VAR:41,WHILE:42}},xa="charAt concat indexOf lastIndexOf match replace search slice split substring toLowerCase toLocaleLowerCase toString toUpperCase toLocaleUpperCase trim".split(" "),ya=new g("break"),za=new g("continue");B.add=function(a,b){return this.evaluate(a)+this.evaluate(b)};B.and=function(a,b){return this.evaluate(a)&&this.evaluate(b)};
B.apply=function(a,b,c){a=this.evaluate(a);b=this.evaluate(b);c=this.evaluate(c);if(!(c instanceof t))throw"Error: Non-List argument given to Apply instruction.";if(null===a||void 0===a)throw"TypeError: Can't read property "+b+" of "+a+".";if("boolean"==typeof a||"number"==typeof a){if("toString"==b)return a.toString();throw"TypeError: "+a+"."+b+" is not a function.";}if("string"==typeof a){if(0<=ia(xa,b))return sa(a[b].apply(a,va(c)));throw"TypeError: "+b+" is not a function";}if(a instanceof t){if(a.has(b)){var d=
a.get(b);if(d instanceof u){var e=va(c);e.unshift(this.w());return d.i.apply(d,e)}throw"TypeError: "+b+" is not a function";}if(0<=ia(y.Fd,b))return e=va(c),e.unshift(this.w()),y[b].apply(a,e)}if(a instanceof u||a instanceof w){if(a.has(b)){d=a.get(b);if(d instanceof u)return e=va(c),e.unshift(this.w()),d.i.apply(d,e);throw"TypeError: "+b+" is not a function";}if("toString"==b)return a instanceof u?a.getName():a.toString();if("hasOwnProperty"==b)return a.has.apply(a,va(c))}throw"TypeError: Object has no '"+
b+"' property.";};B.assign=function(a,b){a=this.evaluate(a);if("string"!=typeof a)throw"Invalid key name given for assignment.";var c=this.w();if(!c.has(a))throw"Attempting to assign to undefined value "+b;var d=this.evaluate(b);c.set(a,d);return d};B["break"]=function(){return ya};B["case"]=function(a){for(var b=this.evaluate(a),c=0;c<b.length;c++){var d=this.evaluate(b[c]);if(d instanceof g)return d}};B["continue"]=function(){return za};
B.Fc=function(a,b,c){var d=new t;b=this.evaluate(b);for(var e=0;e<b.length;e++)d.push(b[e]);var f=[B.Db.FN,a,d].concat(Array.prototype.splice.call(arguments,2,arguments.length-2));this.w().set(a,this.evaluate(f))};B.Ic=function(a,b){return this.evaluate(a)/this.evaluate(b)};B.Kc=function(a,b){return this.evaluate(a)==this.evaluate(b)};B.Mc=function(a){for(var b,c=0;c<arguments.length;c++)b=this.evaluate(arguments[c]);return b};
B.Pc=function(a,b,c){a=this.evaluate(a);b=this.evaluate(b);c=this.evaluate(c);var d=this.w();if("string"==typeof b)for(var e=0;e<b.length;e++){d.set(a,e);var f=this.fa(c);if(f instanceof g){if("break"==f.o)break;if("return"==f.o)return f}}else if(b instanceof w||b instanceof t||b instanceof u){var h=b.H(),k=h.length();for(e=0;e<k;e++)if(d.set(a,h.get(e)),f=this.fa(c),f instanceof g){if("break"==f.o)break;if("return"==f.o)return f}}};B.get=function(a){return this.w().get(this.evaluate(a))};
B.Ab=function(a,b){var c;a=this.evaluate(a);b=this.evaluate(b);if(void 0===a||null===a)throw"TypeError: cannot access property of "+a+".";a instanceof w||a instanceof t||a instanceof u?c=a.get(b):"string"==typeof a&&("length"==b?c=a.length:ba(b)&&(c=a[b]));return c};B.Sc=function(a,b){return this.evaluate(a)>this.evaluate(b)};B.Tc=function(a,b){return this.evaluate(a)>=this.evaluate(b)};B.Xc=function(a,b){return this.evaluate(a)===this.evaluate(b)};B.Yc=function(a,b){return this.evaluate(a)!==this.evaluate(b)};
B["if"]=function(a,b,c){var d=[];this.evaluate(a)?d=this.evaluate(b):c&&(d=this.evaluate(c));var e=this.fa(d);if(e instanceof g)return e};B.ed=function(a,b){return this.evaluate(a)<this.evaluate(b)};B.fd=function(a,b){return this.evaluate(a)<=this.evaluate(b)};B.gd=function(a,b){return this.evaluate(a)%this.evaluate(b)};B.multiply=function(a,b){return this.evaluate(a)*this.evaluate(b)};B.hd=function(a){return-this.evaluate(a)};B.jd=function(a){return!this.evaluate(a)};
B.kd=function(a,b){return this.evaluate(a)!=this.evaluate(b)};B["null"]=function(){return null};B.or=function(a,b){return this.evaluate(a)||this.evaluate(b)};B.Lb=function(a,b){var c=this.evaluate(a);this.evaluate(b);return c};B.Mb=function(a){return this.evaluate(a)};B.quote=function(a){return Array.prototype.slice.apply(arguments)};B["return"]=function(a){return new g("return",this.evaluate(a))};
B.setProperty=function(a,b,c){a=this.evaluate(a);b=this.evaluate(b);c=this.evaluate(c);if(null===a||void 0===a)throw"TypeError: Can't set property "+b+" of "+a+".";(a instanceof u||a instanceof t||a instanceof w)&&a.set(b,c);return c};B.Ed=function(a,b){return this.evaluate(a)-this.evaluate(b)};
B["switch"]=function(a,b,c){a=this.evaluate(a);b=this.evaluate(b);c=this.evaluate(c);if(!ha(b)||!ha(c))throw"Error: Malformed switch instruction.";for(var d,e=!1,f=0;f<b.length;f++)if(e||a===this.evaluate(b[f]))if(d=this.evaluate(c[f]),d instanceof g){var h=d.o;if("break"==h)return;if("return"==h||"continue"==h)return d}else e=!0;if(c.length==b.length+1&&(d=this.evaluate(c[c.length-1]),d instanceof g&&("return"==d.o||"continue"==d.o)))return d};
B.Gd=function(a,b,c){return this.evaluate(a)?this.evaluate(b):this.evaluate(c)};B["typeof"]=function(a){a=this.evaluate(a);return a instanceof u?"function":typeof a};B.undefined=function(){};B["var"]=function(a){for(var b=this.w(),c=0;c<arguments.length;c++){var d=arguments[c];"string"!=typeof d||b.add(d,void 0)}};
B["while"]=function(a,b,c,d){var e,f=this.evaluate(d);if(this.evaluate(c)&&(e=this.fa(f),e instanceof g)){if("break"==e.o)return;if("return"==e.o)return e}for(;this.evaluate(a);){e=this.fa(f);if(e instanceof g){if("break"==e.o)break;if("return"==e.o)return e}this.evaluate(b)}};var Ba=function(){this.Cb=!1;this.ea=new ua;Aa(this);this.Cb=!0};Ba.prototype.cd=function(){return this.Cb};Ba.prototype.isInitialized=Ba.prototype.cd;Ba.prototype.C=function(a){return this.ea.C.apply(this.ea,a)};Ba.prototype.execute=Ba.prototype.C;
var Aa=function(a){function b(a,b){e.ea.rb(a,String(b))}function c(a,b){e.ea.K(String(d[a]),b)}var d=B.Db,e=a;b("control",d.CONTROL);b("fn",d.FN);b("list",d.CREATE_ARRAY);b("map",d.CREATE_OBJECT);b("undefined",d.UNDEFINED);c("ADD",B.add);c("AND",B.and);c("APPLY",B.apply);c("ASSIGN",B.assign);c("BREAK",B["break"]);c("CASE",B["case"]);c("CONTINUE",B["continue"]);c("DEFAULT",B["case"]);c("DEFN",B.Fc);c("DIVIDE",B.Ic);c("EQUALS",B.Kc);c("EXPRESSION_LIST",B.Mc);c("FOR_IN",B.Pc);c("GET",B.get);c("GET_INDEX",
B.Ab);c("GET_PROPERTY",B.Ab);c("GREATER_THAN",B.Sc);c("GREATER_THAN_EQUALS",B.Tc);c("IDENTITY_EQUALS",B.Xc);c("IDENTITY_NOT_EQUALS",B.Yc);c("IF",B["if"]);c("LESS_THAN",B.ed);c("LESS_THAN_EQUALS",B.fd);c("MODULUS",B.gd);c("MULTIPLY",B.multiply);c("NEGATE",B.hd);c("NOT",B.jd);c("NOT_EQUALS",B.kd);c("NULL",B["null"]);c("OR",B.or);c("POST_DECREMENT",B.Lb);c("POST_INCREMENT",B.Lb);c("PRE_DECREMENT",B.Mb);c("PRE_INCREMENT",B.Mb);c("QUOTE",B.quote);c("RETURN",B["return"]);c("SET_PROPERTY",B.setProperty);
c("SUBTRACT",B.Ed);c("SWITCH",B["switch"]);c("TERNARY",B.Gd);c("TYPEOF",B["typeof"]);c("VAR",B["var"]);c("WHILE",B["while"])};Ba.prototype.K=function(a,b){this.ea.K(a,b)};Ba.prototype.addInstruction=Ba.prototype.K;var Ca=function(){this.Da={}};Ca.prototype.get=function(a){return this.Da.hasOwnProperty(a)?this.Da[a]:void 0};Ca.prototype.add=function(a,b){if(this.Da.hasOwnProperty(a))throw"Attempting to add a function which already exists: "+a+".";var c=new u(a,function(){for(var a=Array.prototype.slice.call(arguments,0),c=0;c<a.length;c++)a[c]=this.evaluate(a[c]);return b.apply(this,a)});c.Ea=!0;this.Da[a]=c};Ca.prototype.addAll=function(a){for(var b in a)a.hasOwnProperty(b)&&this.add(b,a[b])};var D=window,E=document,Da=function(a,b){var c=D[a];D[a]=void 0===c?b:c;return D[a]},Ea=function(a){var b=E.getElementsByTagName("script")[0]||E.body||E.head;b.parentNode.insertBefore(a,b)},Fa=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},J=function(a,b,c){var d=E.createElement("script");d.type="text/javascript";d.async=!0;d.src=a;Fa(d,b);c&&(d.onerror=c);Ea(d);return d},Ga=function(a,b){var c=
E.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";Ea(c);Fa(c,b);void 0!==a&&(c.src=a);return c},Ha=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},Ia=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},Ja=function(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)},
P=function(a){D.setTimeout(a,0)},La=function(a){var b=E.getElementById(a);if(b&&Ka(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(Ka(document.all[a][c],"id")==a)return document.all[a][c];return b},Ka=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},Ma=function(a){var b=a.innerText||a.textContent||"";b&&" "!=b&&(b=b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));b&&(b=b.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));return b},Oa=function(a){var b=E.createElement("div");
b.innerHTML="A<div>"+a+"</div>";b=b.lastChild;for(var c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c};var Pa=function(a,b){for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].split("=");if(decodeURIComponent(e[0]).replace(/\+/g," ")==b)return decodeURIComponent(e.slice(1).join("=")).replace(/\+/g," ")}},Q=function(a,b,c,d,e){var f,h=a.protocol||D.location.protocol;h=h.replace(":","").toLowerCase();b&&(b=String(b).toLowerCase());switch(b){case "protocol":f=h;break;case "host":f=(a.hostname||D.location.hostname).split(":")[0].toLowerCase();if(c){var k=/^www\d*\./.exec(f);k&&k[0]&&(f=f.substr(k[0].length))}break;
case "port":f=String(1*(a.hostname?a.port:D.location.port)||("http"==h?80:"https"==h?443:""));break;case "path":f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var l=f.split("/");0<=ia(d||[],l[l.length-1])&&(l[l.length-1]="");f=l.join("/");break;case "query":f=a.search.replace("?","");e&&(f=Pa(f,e));break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},Qa=function(a){var b="";a&&a.href&&(b=a.hash?a.href.replace(a.hash,""):a.href);return b},S=function(a){var b=
E.createElement("a");a&&(b.href=a);return b};var Ta=function(){this.Kb=new Ba;var a=new Ca;a.addAll(Ra());Sa(this,function(b){return a.get(b)})},Ra=function(){return{callInWindow:Ua,getCurrentUrl:Va,getInWindow:Wa,getReferrer:Xa,getUrlComponent:Ya,getUrlFragment:Za,isPlainObject:$a,loadIframe:ab,loadJavaScript:bb,removeUrlFragment:cb,replaceAll:db,sendTrackingBeacon:fb,setInWindow:gb}};Ta.prototype.C=function(a){return this.Kb.C(a)};Ta.prototype.execute=Ta.prototype.C;var Sa=function(a,b){a.Kb.K("require",b)};
function Ua(a,b){for(var c=a.split("."),d=D,e=d[c[0]],f=1;e&&f<c.length;f++)d=e,e=e[c[f]];if("function"==na(e)){var h=[];for(f=1;f<arguments.length;f++)h.push(ra(arguments[f]));e.apply(d,h)}}function Va(){return D.location.href}function Wa(a,b,c){for(var d=a.split("."),e=D,f=0;f<d.length-1;f++)if(e=e[d[f]],void 0===e||null===e)return;b&&(void 0===e[d[f]]||c&&!e[d[f]])&&(e[d[f]]=ra(b));return sa(e[d[f]])}function Xa(){return E.referrer}
function Ya(a,b,c,d,e){var f;if(d&&d instanceof t){f=[];for(var h=Number(d.get("length")),k=0;k<h;k++){var l=d.get(k);"string"==typeof l&&f.push(l)}}return Q(S(a),b,c,f,e)}function Za(a){return Q(S(a),"fragment")}function $a(a){return a instanceof w}function ab(a,b){var c=this.w();Ga(a,function(){b instanceof u&&b.i(c)})}var hb={};
function bb(a,b,c,d){var e=this.w(),f=function(){b instanceof u&&b.i(e)},h=function(){c instanceof u&&c.i(e)};d?hb[d]?(hb[d].onSuccess.push(f),hb[d].onFailure.push(h)):(hb[d]={onSuccess:[f],onFailure:[h]},J(a,function(){for(var a=hb[d].onSuccess,b=0;b<a.length;b++)P(a[b]);a.push=function(a){P(a);return 0}},function(){for(var a=hb[d].onFailure,b=0;b<a.length;b++)P(a[b]);hb[d]=null})):J(a,f,h)}function cb(a){return Qa(S(a))}function db(a,b,c){return a.replace(new RegExp(b,"g"),c)}
function fb(a,b,c){var d=this.w();Ha(a,function(){b instanceof u&&b.i(d)},function(){c instanceof u&&c.i(d)})}function gb(a,b,c){for(var d=a.split("."),e=D,f=0;f<d.length-1;f++)if(e=e[d[f]],void 0===e)return!1;return void 0===e[d[f]]||c?(e[d[f]]=ra(b),!0):!1};var Fb,Gb=[],Ib=[],Jb=[],Kb=[],Lb=[],Mb={},Nb,Ob,Pb=function(a){var b=a["function"];if(!b)throw"Error: No function name given for function call.";if(Mb[b]){var c={},d;for(d in a)a.hasOwnProperty(d)&&0===d.indexOf("vtp_")&&(c[d]=a[d]);return Mb[b](c)}var e=new w,f;for(f in a)a.hasOwnProperty(f)&&0===f.indexOf("vtp_")&&e.set(f.substr(4),sa(a[f]));var h=Fb([b,e]);h instanceof g&&"return"===h.o&&(h=h.getData());return ra(h)},Rb=function(a,b,c){c=c||[];var d={},e;for(e in a)a.hasOwnProperty(e)&&(d[e]=
Qb(a[e],b,c));return d},Qb=function(a,b,c){if(ha(a)){var d;switch(a[0]){case "function_id":return a[1];case "list":d=[];for(var e=1;e<a.length;e++)d.push(Qb(a[e],b,c));return d;case "macro":var f=a[1];if(c[f])return;var h=Gb[f];if(!h||b(h))return;c[f]=!0;d=Pb(Rb(h,b,c));c[f]=!1;return d;case "map":d={};for(var k=1;k<a.length;k+=2)d[Qb(a[k],b,c)]=Qb(a[k+1],b,c);return d;case "template":d=[];for(var l=!1,m=1;m<a.length;m++){var n=Qb(a[m],b,c);Ob&&(l=l||n===Ob.ra);d.push(n)}return Ob&&l?Ob.Bc(d):d.join("");
case "escape":d=Qb(a[1],b,c);if(Ob&&ha(a[1])&&"macro"===a[1][0]&&Ob.dd(a))return Ob.qd(d);d=String(d);for(var p=2;p<a.length;p++)ib[a[p]]&&(d=ib[a[p]](d));return d;case "tag":var q=a[1];if(!Kb[q])throw Error("Unable to resolve tag reference "+q+".");return d={xb:a[2],index:q};case "zb":var v=Sb({"function":a[1],arg0:a[2],arg1:a[3],ignore_case:a[5]},b,c);a[4]&&(v=!v);return v;default:throw Error("Attempting to expand unknown Value type: "+a[0]+".");}}return a},Sb=function(a,b,c){if(b(a))return!1;try{return Nb(Rb(a,
b,c))}catch(d){JSON.stringify(a)}return null};var Tb=null,Wb=function(a){function b(a){for(var b=0;b<a.length;b++)d[a[b]]=!0}var c=[],d=[];Tb=Ub(a);for(var e=0;e<Ib.length;e++){var f=Ib[e],h=Vb(f);if(h){for(var k=f.add||[],l=0;l<k.length;l++)c[k[l]]=!0;b(f.block||[])}else null===h&&b(f.block||[])}var m=[];for(e=0;e<Kb.length;e++)c[e]&&!d[e]&&(m[e]=!0);return m},Vb=function(a){for(var b=a["if"]||[],c=0;c<b.length;c++){var d=Tb(b[c]);if(!d)return null===d?null:!1}var e=a.unless||[];for(c=0;c<e.length;c++){d=Tb(e[c]);if(null===d)return null;if(d)return!1}return!0};
var Ub=function(a){var b=[];return function(c){void 0===b[c]&&(b[c]=Sb(Jb[c],a));return b[c]}};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */
var Zb={},$b=null;Zb.A="AW-836091520";var ac=null,bc={},cc={};var dc=function(){},ec=function(a){return"function"==typeof a},fc=function(a){return"string"==na(a)},gc=function(a){return"number"==na(a)&&!isNaN(a)},hc=function(a){return Math.round(Number(a))||0},ic=function(a){return"false"==String(a).toLowerCase()?!1:!!a},jc=function(a){var b=[];if(ha(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},kc=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},lc=function(a,b){if(!gc(a)||!gc(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-a+1)+
a)},mc=function(){this.prefix="gtm.";this.values={}};mc.prototype.set=function(a,b){this.values[this.prefix+a]=b};mc.prototype.get=function(a){return this.values[this.prefix+a]};mc.prototype.contains=function(a){return void 0!==this.get(a)};var oc=function(){var a=$b.sequence||0;$b.sequence=a+1;return a},pc=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},qc=function(a){var b=!1;return function(){if(!b)try{a()}catch(c){}b=!0}};var rc=function(){var a=function(a){return{toString:function(){return a}}};return{S:a("function"),Sb:a("instance_name"),Tb:a("live_only"),Nd:a("malware_disabled"),Ub:a("once_per_event"),ob:a("once_per_load"),Vb:a("setup_tags"),Wb:a("tag_id"),Xb:a("teardown_tags")}}();var sc=new mc,tc={},wc={set:function(a,b){qa(uc(a,b),tc)},get:function(a){return vc(a,2)},reset:function(){sc=new mc;tc={}}},vc=function(a,b){return 2!=b?sc.get(a):xc(a)},xc=function(a,b,c){var d=a.split(".");var e=function(a,b){for(var c=0;void 0!==a&&c<d.length;c++){if(null===a)return!1;a=a[d[c]]}return void 0!==a||1<c?a:b.length?e(yc(b.pop()),b):zc(d)};return e(tc.eventModel,[b,c]);return zc(d)},zc=function(a){for(var b=tc,c=0;c<a.length;c++){if(null===
b)return!1;if(void 0===b)break;b=b[a[c]]}return b};var yc=function(a){if(a){var b=zc(["gtag","targets",a]);return pa(b)?b:void 0}},Ac=function(a,b){function c(a){if(a)for(var b in a)a.hasOwnProperty(b)&&(d[b]=null)}var d={};c(tc);delete d.eventModel;c(yc(a));c(yc(b));c(tc.eventModel);var e=[],f;for(f in d)d.hasOwnProperty(f)&&e.push(f);return e};
var Bc=function(a,b){sc.set(a,b);qa(uc(a,b),tc)},uc=function(a,b){for(var c={},d=c,e=a.split("."),f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c};var Cc=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),Dc={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},Ec={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},Fc=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c};
var Gc=function(a){var b=vc("gtm.whitelist");b="gtagua gtagaw gtagfl e v oid op cn css ew eq ge gt lc le lt re sw um".split(" ");var c=b&&Fc(jc(b),Dc),d=vc("gtm.blacklist")||
vc("tagTypeBlacklist")||[];Cc.test(D.location&&D.location.hostname)&&(d=jc(d),d.push("nonGooglePixels","nonGoogleScripts"));var e=d&&Fc(jc(d),Ec),f={};return function(h){var k=h&&h[rc.S];if(!k||"string"!=typeof k)return!0;k=k.replace(/_/g,"");if(void 0!==f[k])return f[k];var l=cc[k]||[],m=a(k);if(b){var n;if(n=m)a:{if(0>ia(c,k))if(l&&0<l.length)for(var p=0;p<l.length;p++){if(0>
ia(c,l[p])){n=!1;break a}}else{n=!1;break a}n=!0}m=n}var q=!1;if(d){var v;if(!(v=0<=ia(e,k)))a:{for(var r=l||[],x=new mc,F=0;F<e.length;F++)x.set(e[F],!0);for(F=0;F<r.length;F++)if(x.get(r[F])){v=!0;break a}v=!1}q=v}return f[k]=!m||q}};var Hc=function(a){var b=$b.zones;!b&&a&&(b=$b.zones=a());return b},Ic={active:!0,isWhitelisted:function(){return!0}};var Jc=!1,Kc=0,Lc=[];function Mc(a){if(!Jc){var b=E.createEventObject,c="complete"==E.readyState,d="interactive"==E.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){Jc=!0;for(var e=0;e<Lc.length;e++)P(Lc[e])}Lc.push=function(){for(var a=0;a<arguments.length;a++)P(arguments[a]);return 0}}}function Nc(){if(!Jc&&140>Kc){Kc++;try{E.documentElement.doScroll("left"),Mc()}catch(a){D.setTimeout(Nc,50)}}}var Oc=function(a){Jc?a():Lc.push(a)};var Pc=!1;var Qc=function(a){D.GoogleAnalyticsObject||(D.GoogleAnalyticsObject=a||"ga");var b=D.GoogleAnalyticsObject;if(!D[b]){var c=function(){c.q=c.q||[];c.q.push(arguments)};c.l=Number(new Date);D[b]=c}return D[b]},Rc=function(){return D.GoogleAnalyticsObject&&D[D.GoogleAnalyticsObject]},Sc=function(a,b,c,d){b=String(b).replace(/\s+/g,"").split(",");var e=Rc();e(a+"require","linker");e(a+"linker:autoLink",b,c,d)};function Wc(a,b,c,d,e,f){var h=Kb[a],k=Xc(a,b,c,d,e,f);if(!k)return null;var l=Qb(h[rc.Vb],f.la,[]);if(l&&l.length){var m=l[0];k=Wc(m.index,b,k,1===m.xb?e:k,e,f)}return k}
function Xc(a,b,c,d,e,f){function h(){var a=Rb(k,f.la);a.vtp_gtmOnSuccess=c;a.vtp_gtmOnFailure=d;a.vtp_gtmTagId=k.tag_id;Pb(a)}var k=Kb[a];if(f.la(k))return null;var l=Qb(k[rc.Xb],f.la,[]);if(l&&l.length){var m=l[0],n=Wc(m.index,b,c,d,e,f);if(!n)return null;c=n;d=2===m.xb?e:n}if(k[rc.ob]||k[rc.Ub]){var p=k[rc.ob]?Lb:b,q=c,v=d;if(!p[a]){h=qc(h);var r=Yc(a,p,h);c=r.J;d=r.W}return function(){p[a](q,v)}}return h}
function Yc(a,b,c){var d=[],e=[];b[a]=Zc(d,e,c);return{J:function(){b[a]=$c;for(var c=0;c<d.length;c++)d[c]()},W:function(){b[a]=ad;for(var c=0;c<e.length;c++)e[c]()}}}function Zc(a,b,c){return function(d,e){a.push(d);b.push(e);c()}}function $c(a){a()}function ad(a,b){b()};function bd(a){var b=0,c=0,d=!1;return{add:function(){c++;return qc(function(){b++;d&&b>=c&&a()})},gc:function(){d=!0;b>=c&&a()}}}function cd(a,b){return function(){try{a()}catch(c){b()}}}var dd=!1;var ed=function(a,b){var c={};c[rc.S]="__"+a;for(var d in b)b.hasOwnProperty(d)&&(c["vtp_"+d]=b[d]);for(d in void 0)(void 0).hasOwnProperty(d)&&(c[d]=(void 0)[d]);Kb.push(c);return Kb.length-1};var fd=/[A-Z]+/,gd=/\s/,hd=function(a){if(fc(a)&&(a=a.trim(),!gd.test(a))){var b=a.indexOf("-");if(!(0>b)){var c=a.substring(0,b);if(fd.test(c)){for(var d=a.substring(b+1).split("/"),e=0;e<d.length;e++)if(!d[e])return;return{id:a,prefix:c,containerId:c+"-"+d[0],ja:d}}}}};var id=null,jd={},kd={},ld;function md(){id=id||!$b.gtagRegistered;$b.gtagRegistered=!0;return id}var nd=function(a,b){var c={event:a};b&&(c.eventModel=qa(b,void 0),b.event_callback&&(c.eventCallback=b.event_callback),b.event_timeout&&(c.eventTimeout=b.event_timeout));return c};
function od(a){if(void 0===kd[a.id]){var b;if("UA"==a.prefix)b=ed("gtagua",{trackingId:a.id});else if("AW"==a.prefix)b=ed("gtagaw",{conversionId:a});else if("DC"==a.prefix)b=ed("gtagfl",{targetId:a.id});else return;if(!ld){var c={name:"send_to",dataLayerVersion:2},d={};d[rc.S]="__v";for(var e in c)c.hasOwnProperty(e)&&(d["vtp_"+e]=c[e]);Gb.push(d);ld=["macro",Gb.length-1]}var f={arg0:ld,arg1:a.id,ignore_case:!1};f[rc.S]="_lc";Jb.push(f);var h={"if":[Jb.length-1],add:[b]};h["if"]&&(h.add||h.block)&&
Ib.push(h);kd[a.id]=b}}
var td={event:function(a){var b=a[1];if(fc(b)&&!(3<a.length)){var c;if(2<a.length){if(!pa(a[2]))return;c=a[2]}var d=nd(b,c);var e;var f=c,h=vc("gtag.fields.send_to",2);fc(h)||(h="send_to");var k=f&&f[h];void 0===k&&(k=vc(h,2),void 0===k&&(k="default"));if(fc(k)||ha(k)){for(var l,m=k.toString().replace(/\s+/g,"").split(","),n=[],p=0;p<m.length;p++)0<=m[p].indexOf("-")?n.push(m[p]):n=n.concat(jd[m[p]]||[]);l=n;for(var q={},v=0;v<l.length;++v){var r=hd(l[v]);r&&(q[r.id]=
r)}var x=[],F;for(F in q)if(q.hasOwnProperty(F)){var X=q[F];"AW"===X.prefix&&X.ja[1]&&x.push(X.containerId)}for(var A=0;A<x.length;++A)delete q[x[A]];var M=[],C;for(C in q)q.hasOwnProperty(C)&&M.push(q[C]);e=M}else e=void 0;if(!e)return;var N=md();N||pd();for(var I=[],K=0;N&&K<e.length;K++){var G=e[K];I.push(G.id);od(G)}d.eventModel=d.eventModel||{};0<e.length?d.eventModel.send_to=I.join():delete d.eventModel.send_to;return d}},set:function(a){var b;2==a.length&&pa(a[1])?
b=qa(a[1],void 0):3==a.length&&fc(a[1])&&(b={},b[a[1]]=a[2]);if(b)return b.eventModel=qa(b,void 0),b.event="gtag.set",b._clear=!0,b},js:function(a){if(2==a.length&&a[1].getTime)return{event:"gtm.js","gtm.start":a[1].getTime()}},config:function(a){var b=a[2]||{};if(2>a.length||!fc(a[1])||!pa(b))return;var c=hd(a[1]);if(!c)return;md()?od(c):pd();var d=c.id,e;for(e in jd)if(jd.hasOwnProperty(e)){var f=ia(jd[e],d);0<=f&&jd[e].splice(f,1)}var h=c.id,k=b.groups||"default";
k=k.toString().split(",");for(var l=0;l<k.length;l++)jd[k[l]]=jd[k[l]]||[],jd[k[l]].push(h);delete b.groups;Bc("gtag.targets."+c.id,void 0);Bc("gtag.targets."+c.id,qa(b,void 0));return nd("gtag.config",{send_to:c.id});}},pd=qc(function(){});var ud=!1,vd=[];function wd(){if(!ud){ud=!0;for(var a=0;a<vd.length;a++)P(vd[a])}};var xd=[],yd=!1,zd=function(a){var b=a.eventCallback,c=qc(function(){ec(b)&&P(function(){b(Zb.A)})}),d=a.eventTimeout;d&&D.setTimeout(c,Number(d));return c},Ad=function(){for(var a=!1;!yd&&0<xd.length;){yd=!0;delete tc.eventModel;var b=xd.shift();if(ec(b))try{b.call(wc)}catch(qd){}else if(ha(b)){var c=b;if(fc(c[0])){var d=c[0].split("."),e=d.pop(),f=c.slice(1),h=vc(d.join("."),2);if(void 0!==h&&null!==h)try{h[e].apply(h,f)}catch(qd){}}}else{var k=b;if(k&&("[object Arguments]"==Object.prototype.toString.call(k)||
Object.prototype.hasOwnProperty.call(k,"callee"))){a:{var l=b;if(l.length&&fc(l[0])){var m=td[l[0]];if(m){b=m(l);break a}}b=void 0}if(!b){yd=!1;continue}}var n;var p=void 0,q=b,v=q._clear;for(p in q)q.hasOwnProperty(p)&&"_clear"!==p&&(v&&Bc(p,void 0),Bc(p,q[p]));var r=q.event;if(r){var x=q["gtm.uniqueEventId"];x||(x=oc(),q["gtm.uniqueEventId"]=x,Bc("gtm.uniqueEventId",x));ac=r;var F;var X,A,M=q,C=M.event,N=M["gtm.uniqueEventId"],I=$b.zones;A=I?I.checkState(Zb.A,N):Ic;if(A.active){var K=zd(M);c:{var G=
A.isWhitelisted;if("gtm.js"==C){if(dd){X=!1;break c}dd=!0}var L={id:N,name:C,vc:K||dc,la:Gc(G)};L.cb=Wb(L.la);for(var wa,Na=L,pb=bd(Na.vc),Je=[],Hb=[],qb=0;qb<Na.cb.length;qb++)if(Na.cb[qb]){var Ke=Kb[qb];var eb=pb.add();
try{var rd=Wc(qb,Je,eb,eb,eb,Na);rd?Hb.push(cd(rd,eb)):eb()}catch(qd){eb()}}pb.gc();for(var nc=0;nc<Hb.length;nc++)Hb[nc]();wa=0<Hb.length;if("gtm.js"===C||"gtm.sync"===C)d:{}X=wa}F=X?!0:!1}else F=!1;ac=null;n=F}else n=!1;a=n||a}yd=!1}return!a},Bd=function(){return Ad()},Cd=function(){var a=Da("dataLayer",[]),b=Da("google_tag_manager",{});b=b["dataLayer"]=
b["dataLayer"]||{};Lc.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});vd.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(xd.push.apply(xd,b);300<this.length;)this.shift();return Ad()};xd.push.apply(xd,a.slice(0));P(Bd)};var T={};T.ra=new String("undefined");T.Ka={};var Dd=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===T.ra?b:a[d]);return c.join("")}};Dd.prototype.toString=function(){return this.resolve("undefined")};Dd.prototype.valueOf=Dd.prototype.toString;T.Bc=function(a){return new Dd(a)};var Ed={};T.wd=function(a,b){var c=oc();Ed[c]=[a,b];return c};T.tb=function(a){var b=a?0:1;return function(a){var c=Ed[a];if(c&&"function"===typeof c[b])c[b]();Ed[a]=void 0}};
T.dd=function(a){for(var b=!1,c=!1,d=2;d<a.length;d++)b=b||8===a[d],c=c||16===a[d];return b&&c};T.qd=function(a){if(a===T.ra)return a;var b=oc();T.Ka[b]=a;return'google_tag_manager["'+Zb.A+'"].macro('+b+")"};T.Yb=Dd;var Fd=new mc,Gd=function(a,b){function c(a){var b=S(a),c=Q(b,"protocol"),d=Q(b,"host",!0),e=Q(b,"port"),f=Q(b,"path").toLowerCase().replace(/\/$/,"");if(void 0===c||"http"==c&&"80"==e||"https"==c&&"443"==e)c="web",e="default";return[c,d,e,f]}for(var d=c(String(a)),e=c(String(b)),f=0;f<d.length;f++)if(d[f]!==e[f])return!1;return!0};
function Hd(a){var b=a.arg0,c=a.arg1;switch(a["function"]){case "_cn":return 0<=String(b).indexOf(String(c));case "_css":var d;a:{if(b){var e=["matches","webkitMatchesSelector","mozMatchesSelector","msMatchesSelector","oMatchesSelector"];try{for(var f=0;f<e.length;f++)if(b[e[f]]){d=b[e[f]](c);break a}}catch(r){}}d=!1}return d;case "_ew":var h,k;h=String(b);k=String(c);var l=h.length-k.length;return 0<=l&&h.indexOf(k,l)==l;case "_eq":return String(b)==String(c);case "_ge":return Number(b)>=Number(c);
case "_gt":return Number(b)>Number(c);case "_lc":var m;m=b.toString().split(",");return 0<=ia(m,String(c));case "_le":return Number(b)<=Number(c);case "_lt":return Number(b)<Number(c);case "_re":var n;var p=a.ignore_case?"i":void 0;try{var q=String(c)+p,v=Fd.get(q);v||(v=new RegExp(c,p),Fd.set(q,v));n=v.test(b)}catch(r){n=!1}return n;case "_sw":return 0==String(b).indexOf(String(c));case "_um":return Gd(b,c)}return!1};function Id(a,b,c,d){return(d||"https:"==D.location.protocol?a:b)+c}function Jd(a,b){for(var c=b||(a instanceof t?new t:new w),d=a.H(),e=Number(d.get("length")),f=0;f<e;f++){var h=d.get(f);if(a.has(h)){var k=a.get(h);k instanceof t?(c.get(h)instanceof t||c.set(h,new t),Jd(k,c.get(h))):k instanceof w?(c.get(h)instanceof w||c.set(h,new w),Jd(k,c.get(h))):c.set(h,k)}}return c}function Kd(){return Zb.A}function Ld(){return(new Date).getTime()}function Md(a,b){return sa(vc(a,b||2))}
function Nd(){return ac}function Od(a){return Oa('<a href="'+a+'"></a>')[0].href}function Pd(a){return hc(ra(a))}function Qd(a){return null===a?"null":void 0===a?"undefined":a.toString()}function Rd(a,b){return lc(a,b)}function Sd(a,b,c){if(!(a instanceof t))return null;for(var d=new w,e=!1,f=a.get("length"),h=0;h<f;h++){var k=a.get(h);k instanceof w&&k.has(b)&&k.has(c)&&(d.set(k.get(b),k.get(c)),e=!0)}return e?d:null}
var Td=function(){var a=new Ca;a.addAll(Ra());a.addAll({buildSafeUrl:Id,decodeHtmlUrl:Od,copy:Jd,generateUniqueNumber:oc,getContainerId:Kd,getCurrentTime:Ld,getDataLayerValue:Md,getEventName:Nd,makeInteger:Pd,makeString:Qd,randomInteger:Rd,tableToMap:Sd});return function(b){return a.get(b)}};var Ud=new Ta,Vd=function(){var a=data.runtime||[];Fb=function(a){return Ud.C(a)};Nb=Hd;Sa(Ud,Td());for(var b=0;b<a.length;b++){var c=a[b];if(!ha(c)||3>c.length){if(0==c.length)continue;break}Ud.C(c)}};var Wd=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var Xd=function(a){return encodeURIComponent(a)},Yd=function(a){var b=["veinteractive.com","ve-interactive.cn"];if(!a)return!1;var c=Q(S(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1};
var U=function(a,b,c){for(var d={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(c)&&(d[a[f][b]]=a[f][c],e=!0);return e?d:null},Zd=function(a,b){qa(a,b)},$d=function(a){return hc(a)},ae=function(a,b){return ia(a,b)};var be=function(a){var b={"gtm.element":a,"gtm.elementClasses":a.className,"gtm.elementId":a["for"]||Ka(a,"id")||"","gtm.elementTarget":a.formTarget||a.target||""};b["gtm.elementUrl"]=(a.attributes&&a.attributes.formaction?a.formAction:"")||a.action||a.href||a.src||a.code||a.codebase||"";return b},ce=function(a){$b.hasOwnProperty("autoEventsSettings")||($b.autoEventsSettings={});var b=$b.autoEventsSettings;b.hasOwnProperty(a)||(b[a]={});return b[a]},de=function(a,b,c,d){var e=ce(a),f=pc(e,b,d);e[b]=
c(f)},ee=function(a,b,c){var d=ce(a);return pc(d,b,c)};var fe=/(^|\.)doubleclick\.net$/i,ge=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,he=function(a,b,c){for(var d=String(b||E.cookie).split(";"),e=[],f=0;f<d.length;f++){var h=d[f].split("="),k=kc(h[0]);if(k&&k==a){var l=kc(h.slice(1).join("="));l&&!1!==c&&(l=decodeURIComponent(l));e.push(l)}}return e},ie=function(a,b,c,d,e){b=encodeURIComponent(b);var f=a+"="+b+"; ";c&&(f+="path="+c+"; ");e&&(f+="expires="+e.toGMTString()+"; ");var h,k;if("auto"==d){var l=Q(D.location,"host",!0).split(".");if(4==l.length&&
/^[0-9]*$/.exec(l[3]))k=["none"];else{for(var m=[],n=l.length-2;0<=n;n--)m.push(l.slice(n).join("."));m.push("none");k=m}}else k=[d||"none"];h=k;for(var p=E.cookie,q=0;q<h.length;q++){var v=f,r=h[q],x=c;if(fe.test(D.location.hostname)||"/"==x&&ge.test(r))break;"none"!=h[q]&&(v+="domain="+h[q]+";");E.cookie=v;if(p!=E.cookie||0<=ia(he(a),b))break}};var je=!1;if(E.querySelectorAll)try{var ke=E.querySelectorAll(":root");ke&&1==ke.length&&ke[0]==E.documentElement&&(je=!0)}catch(a){}var le=je;var me=function(a){for(var b=[],c=E.cookie.split(";"),d=new RegExp("^\\s*"+a+"=\\s*(.*?)\\s*$"),e=0;e<c.length;e++){var f=c[e].match(d);f&&b.push(f[1])}var h=[];if(!b||0==b.length)return h;for(var k=0;k<b.length;k++){var l=b[k].split(".");3==l.length&&"GCL"==l[0]&&l[1]&&h.push(l[2])}return h};var ne=/^\w+$/,oe=/^[\w-]+$/,pe=/^\d+\.fls\.doubleclick\.net$/;function qe(a){return a&&"string"==typeof a&&a.match(ne)?a:"_gcl"}function re(a){if(a){if("string"==typeof a){var b=qe(a);return{da:b,ca:b}}if(a&&"object"==typeof a)return{da:qe(a.dc),ca:qe(a.aw)}}return{da:"_gcl",ca:"_gcl"}}function se(a){var b=S(D.location.href),c=Q(b,"host",!1);if(c&&c.match(pe)){var d=Q(b,"path").split(a+"=");if(1<d.length)return d[1].split(";")[0].split("?")[0]}}
function te(a){return a.filter(function(a){return oe.test(a)})}var ve=function(a){var b=se("gclaw");if(b)return b.split(".");var c=re(a);if("_gcl"==c.ca){var d=ue();if(d&&(null==d.G||"aw.ds"==d.G))return[d.ha]}return te(me(c.ca+"_aw"))},we=function(a){var b=se("gcldc");if(b)return b.split(".");var c=re(a);if("_gcl"==c.da){var d=ue();if(d&&("ds"==d.G||"aw.ds"==d.G))return[d.ha]}return te(me(c.da+"_dc"))};
function ue(){var a=S(D.location.href),b=Q(a,"query",!1,void 0,"gclid"),c=Q(a,"query",!1,void 0,"gclsrc");if(!b||!c){var d=Q(a,"fragment");b=b||Pa(d,"gclid");c=c||Pa(d,"gclsrc")}return void 0!==b&&b.match(oe)?{ha:b,G:c}:null}
var xe=function(a,b,c){var d=re(a);c=c||"auto";b=b||"/";var e=ue();if(null!=e){var f=(new Date).getTime(),h=new Date(f+7776E6),k=["GCL",Math.round(f/1E3),e.ha].join(".");e.G&&"aw.ds"!=e.G||ie(d.ca+"_aw",k,b,c,h);"aw.ds"!=e.G&&"ds"!=e.G||ie(d.da+"_dc",k,b,c,h)}},ye=function(){var a=se("gac");if(a)return decodeURIComponent(a);for(var b=[],c=E.cookie.split(";"),d=/^\s*_gac_(UA-\d+-\d+)=\s*(.+?)\s*$/,e=0;e<c.length;e++){var f=c[e].match(d);f&&b.push({gb:f[1],value:f[2]})}var h={};if(b&&b.length)for(var k=
0;k<b.length;k++){var l=b[k].value.split(".");"1"==l[0]&&3==l.length&&l[1]&&(h[b[k].gb]||(h[b[k].gb]=[]),h[b[k].gb].push({timestamp:l[1],ha:l[2]}))}var m=[],n;for(n in h)if(h.hasOwnProperty(n)){for(var p=[],q=h[n],v=0;v<q.length;v++)p.push(q[v].ha);p=te(p);p.length&&m.push(n+":"+p.join(","))}return m.join(";")};var ze;a:{ze="g";break a;ze="G"}var Ae={"":"n",UA:"u",AW:"a",DC:"d",GTM:ze},Be=function(a){var b=Zb.A.split("-"),c=b[0].toUpperCase();return(Ae[c]||"i")+"2r"+(a&&"GTM"===c?b[1]:"")};
var Ce=function(a){return!(void 0===a||null===a||0===(a+"").length)},De=function(a,b){var c;if(2===b.B)return a("ord",lc(1E11,1E13)),!0;if(3===b.B)return a("ord","1"),a("num",lc(1E11,1E13)),!0;if(4===b.B)return Ce(b.sessionId)&&a("ord",b.sessionId),!0;if(5===b.B)c="1";else if(6===b.B)c=b.Nb;else return!1;Ce(c)&&a("qty",c);Ce(b.Oa)&&a("cost",b.Oa);Ce(b.hb)&&a("ord",b.hb);return!0},Ee=encodeURIComponent,Fe=function(a,b){function c(a,b,c){f.hasOwnProperty(a)||(b+="",e+=";"+a+"="+(c?b:Ee(b)))}var d=a.Qa,
e=a.protocol;e+=a.Ha?"//"+d+".fls.doubleclick.net/activityi":"//ad.doubleclick.net/activity";e+=";src="+Ee(d)+(";type="+Ee(a.Ra))+(";cat="+Ee(a.ba));var f=a.Dc||{},h;for(h in f)f.hasOwnProperty(h)&&(e+=";"+Ee(h)+"="+Ee(f[h]+""));if(De(c,a)){Ce(a.jb)&&c("u",a.jb);Ce(a.tran)&&c("tran",a.tran);c("gtm",Be());if(a.Na){var k=we(a.Aa);k&&k.length&&c("gcldc",k.join("."));var l=ve(a.Aa);l&&l.length&&c("gclaw",l.join("."));var m=ye();m&&c("gac",m)}Ce(a.Ya)&&c("prd",a.Ya,!0);for(var n in a.na)a.na.hasOwnProperty(n)&&
c(n,a.na[n]);e+=b||"";Ce(a.Fa)&&c("~oref",a.Fa);a.Ha?Ga(e+"?",a.J):Ha(e+"?",a.J,a.W)}else P(a.W)};var Re="www.googletagmanager.com/gtm.js";Re="www.googletagmanager.com/gtag/js";
var Se=Re,Te=function(a,b,c,d){Ia(a,b,c,d)},Ue=function(a,b){return D.setTimeout(a,b)},Ve=function(a,b,c){J(a,b,c)},We={},Xe=function(a,b,c){var d=We[a];if(void 0===d){var e=function(a,b){return function(){a.status=b;for(var c=2==b?a.Qb:a.wb,d=0;d<c.length;d++)D.setTimeout(c[d],0)}};d={status:1,Qb:[],wb:[],Ad:void 0};d.ae=J(a,e(d,2),e(d,3));We[a]=d}0===d.status&&(d.Ad(),d.status=2);2===d.status?b&&b():3===d.status?c&&c():1===d.status&&(b&&d.Qb.push(b),c&&d.wb.push(c))},Ye=function(){return D.location.href},
Ze=function(a){return Q(S(a),"fragment")},V=function(a,b){return vc(a,b||2)},$e=function(a,b,c){b&&(a.eventCallback=b,c&&(a.eventTimeout=c));return D["dataLayer"].push(a)},af=function(a,b){D[a]=b},W=function(a,b,c){b&&(void 0===D[a]||c&&!D[a])&&(D[a]=b);return D[a]},bf=function(a,b){var c;a:{var d;d=100;for(var e={},f=0;f<b.length;f++)e[b[f]]=!0;for(var h=a,k=0;h&&k<=d;k++){if(e[String(h.tagName).toLowerCase()]){c=h;break a}h=h.parentElement}c=null}return c},Y=function(a,b,c,d){var e=!d&&"http:"==
D.location.protocol;e&&(e=2!==cf());return(e?b:a)+c};
var df=function(a){var b=0;return b},ef=function(a){},ff=function(a){var b=!1;return b},gf=function(a,b){var c;a:{if(a&&
ha(a))for(var d=0;d<a.length;d++)if(a[d]&&b(a[d])){c=a[d];break a}c=void 0}return c},hf=function(a,b,c,d){de(a,b,c,d)},jf=function(a,b,c){return ee(a,b,c)},kf=function(a){return!!ee(a,"init",!1)},lf=function(a){ce(a).init=!0};
var nf=void 0,of=function(a){if(!nf){var b=function(){var a=E.body;if(a)if(W("MutationObserver"))(new MutationObserver(function(){for(var a=0;a<nf.length;a++)P(nf[a])})).observe(a,{childList:!0,subtree:!0});else{var b=!1;Te(a,"DOMNodeInserted",function(){b||(b=!0,P(function(){b=!1;for(var a=0;a<nf.length;a++)P(nf[a])}))})}};nf=[];E.body?b():P(b)}nf.push(a)},cf=function(){var a=Se;a=a.toLowerCase();for(var b="https://"+a,c="http://"+a,d=1,e=E.getElementsByTagName("script"),f=0;f<e.length&&100>f;f++){var h=
e[f].src;if(h){h=h.toLowerCase();if(0===h.indexOf(c))return 3;1===d&&0===h.indexOf(b)&&(d=2)}}return d};var pf=function(a,b){return xc(a,b,void 0)};
var qf=function(a){var b=Se+"?id="+encodeURIComponent(a)+"&l=dataLayer",c=Y("https://","http://",b);J(c,void 0,void 0)};var sf=function(a,b,c){a instanceof T.Yb&&(a=a.resolve(T.wd(b,c)),b=dc);return{Sa:a,J:b}};var Z={a:{}};

Z.a.e=["google"],function(){(function(a){Z.__e=a;Z.__e.b="e";Z.__e.g=!0})(function(){return ac})}();
Z.a.v=["google"],function(){(function(a){Z.__v=a;Z.__v.b="v";Z.__v.g=!0})(function(a){var b=V(a.vtp_name.replace(/\\\./g,"."),a.vtp_dataLayerVersion||1);return void 0!==b?b:a.vtp_defaultValue})}();
Z.a.gtagaw=["google"],function(){var a=!1,b=!1,c=[],d="send_to aw_remarketing aw_remarketing_only custom_params send_page_view language value currency transaction_id user_id conversion_linker conversion_cookie_prefix page_location page_referrer phone_conversion_number phone_conversion_callback phone_conversion_css_class items aw_merchant_id aw_feed_country aw_feed_language discount transaction_id enable_mrc".split(" "),e=function(a){var b=W("google_trackConversion"),c=a.gtm_onFailure;"function"==
typeof b?b(a)||c():c()},f=function(){for(;0<c.length;)e(c.shift())},h=function(){a||(a=!0,Ve(Y("https://","http://","www.googleadservices.com/pagead/conversion_async.js"),function(){f();c={push:e}},function(){f();a=!1}))},k=function(a,c,d,e){if(c){var f=a.ja[0],h=a.ja[1],k=W("_googWcmImpl",function(){k.q=k.q||[];k.q.push(arguments)});W("_googWcmAk",f);b||(b=!0,Ve(Y("https://","http://","www.gstatic.com/wcm/loader.js")));var l={ak:f,cl:h};void 0===d&&(l.autoreplace=c);k(2,d,l,c,e,new Date,e)}},l=function(a){if(a){for(var b=
[],c=0;c<a.length;++c){var d=a[c];d&&b.push({item_id:d.id,quantity:d.quantity,value:d.price})}return b}};(function(a){Z.__gtagaw=a;Z.__gtagaw.b="gtagaw";Z.__gtagaw.g=!0})(function(a){var b=a.vtp_conversionId,e=ac,f="gtag.config"==e,m=b.ja[0],r=b.ja[1],x=void 0!==r,F=b.containerId,X=x?b.id:void 0,A=function(a){return xc(a,F,X)},M=!1!==A("conversion_linker"),C=A("conversion_cookie_prefix");f&&M&&xe(C,void 0,void 0);if(f&&x){var N=A("phone_conversion_number"),I=A("phone_conversion_callback"),K=A("phone_conversion_css_class"),
G=A("phone_conversion_options");k(b,N,I||K,G)}var L=!1===A("aw_remarketing")||!1===A("send_page_view");if(!f||!x&&!L){!0===A("aw_remarketing_only")&&(x=!1);var H={google_conversion_id:m,google_remarketing_only:!x,onload_callback:a.vtp_gtmOnSuccess,gtm_onFailure:a.vtp_gtmOnFailure,google_conversion_format:"3",google_conversion_color:"ffffff",google_conversion_domain:"",google_conversion_label:r,google_conversion_language:A("language"),google_conversion_value:A("value"),google_conversion_currency:A("currency"),
google_conversion_order_id:A("transaction_id"),google_user_id:A("user_id"),google_conversion_page_url:A("page_location"),google_conversion_referrer_url:A("page_referrer"),google_gtm:Be(void 0),google_read_gcl_cookie_opt_out:!M};M&&C&&(pa(C)?H.google_gcl_cookie_prefix=C.aw:H.google_gcl_cookie_prefix=C);var O=function(){var a=A("custom_params"),b={event:e};if(ha(a)){for(var c=0;c<a.length;++c){var f=a[c],h=A(f);void 0!==h&&(b[f]=h)}return b}var k=A("eventModel");if(!k)return null;qa(k,b);for(var l=
0;l<d.length;++l)delete b[d[l]];return b}();O&&(H.google_custom_params=O);if(x&&"purchase"==e&&A("aw_merchant_id")){H.google_conversion_merchant_id=A("aw_merchant_id");H.google_basket_feed_country=A("aw_feed_country");H.google_basket_feed_language=A("aw_feed_language");H.google_basket_discount=A("discount");H.google_basket_transaction_type=e;H.google_disable_merchant_reported_conversions=!0!==A("enable_mrc");var R=l(A("items"));R&&(H.google_conversion_items=R)}c.push(H)}h()})}();




Z.a.gtagfl=[],function(){function a(a){var b=/^DC-(\d+)(\/([\w-]+)\/([\w-]+)\+(\w+))?$/.exec(a);if(b){var c={standard:2,unique:3,per_session:4,transactions:5,items_sold:6,"":1}[(b[5]||"").toLowerCase()];if(c)return{containerId:"DC-"+b[1],Rb:b[3]?a:"",ac:b[1],$b:b[3]||"",ba:b[4]||"",B:c}}}function b(a,b){function c(b,c,e){void 0!==e&&0!==(e+"").length&&d.push(b+c+":"+a(e+""))}var d=[],e=b("items")||[];if(ha(e))for(var l=0;l<e.length;l++){var m=e[l],n=l+1;c("i",n,m.id);c("p",n,m.price);c("q",n,m.quantity);
c("c",n,b("country"));c("l",n,b("language"))}return d.join("|")}function c(a,b,c){var d=/^u([1-9]\d?|100)$/,e=a("custom_map")||{},f=Ac(b,c),m={},n={};if(pa(e))for(var p in e)if(e.hasOwnProperty(p)&&d.test(p)){var q=e[p];fc(q)&&(m[p]=q)}for(var v=0;v<f.length;v++){var r=f[v];d.test(r)&&(m[r]=r)}for(var x in m)m.hasOwnProperty(x)&&(n[x]=a(m[x]));return n}(function(a){Z.__gtagfl=a;Z.__gtagfl.b="gtagfl";Z.__gtagfl.g=!0})(function(d){var e=d.vtp_gtmOnSuccess,f=d.vtp_gtmOnFailure,h=a(d.vtp_targetId);if(h){var k=
function(a){return xc(a,h.containerId,h.Rb||void 0)},l=!1!==k("conversion_linker"),m=k("conversion_cookie_prefix");if("gtag.config"===ac)l&&xe(m,void 0,void 0),P(e);else{var n={},p=k("dc_custom_params");if(pa(p))for(var q in p)if(p.hasOwnProperty(q)){var v=p[q];void 0!==v&&null!==v&&(n[q]=v)}var r="";if(5===h.B||6===h.B)r=b(Xd,k);var x=c(k,h.containerId,h.Rb),F=3===cf(),X=!0===k("allow_custom_scripts"),A={ba:h.ba,Na:l,Aa:m,Oa:k("value"),B:h.B,Dc:n,Qa:h.ac,Ra:h.$b,W:f,J:e,Fa:Qa(S(Ye())),Ya:r,protocol:F?
"http:":"https:",Nb:k("quantity"),Ha:X,sessionId:k("session_id"),hb:k("transaction_id"),na:x};Fe(A,void 0)}}else P(f)})}();


Z.a.gtagua=["google"],function(){var a,b={client_id:1,client_storage:"storage",cookie_name:1,cookie_domain:1,cookie_expires:1,cookie_update:1,sample_rate:1,site_speed_sample_rate:1,use_amp_client_id:1,store_gac:1,conversion_linker:"storeGac"},c={anonymize_ip:1,app_id:1,app_installer_id:1,app_name:1,app_version:1,campaign:{name:"campaignName",source:"campaignSource",medium:"campaignMedium",term:"campaignTerm",content:"campaignContent",id:"campaignId"},currency:"currencyCode",description:"exDescription",
fatal:"exFatal",language:1,non_interaction:1,page_hostname:"hostname",page_referrer:"referrer",page_path:"page",page_location:"location",page_title:"title",screen_name:1,transport_type:"transport",user_id:1},d={content_id:1,event_category:1,event_action:1,event_label:1,link_attribution:1,linker:1,method:1,name:1,send_page_view:1,value:1},e={cookie_name:1,cookie_expires:"duration",levels:1},f={anonymize_ip:1,fatal:1,non_interaction:1,use_amp_client_id:1,send_page_view:1,store_gac:1,conversion_linker:1},
h=function(a,b,c,d){if(void 0!==c)if(f[b]&&(c=ic(c)),"anonymize_ip"!=b||c||(c=void 0),1===a)d[k(b)]=c;else if(fc(a))d[a]=c;else for(var e in a)a.hasOwnProperty(e)&&void 0!==c[e]&&(d[a[e]]=c[e])},k=function(a){return a&&fc(a)?a.replace(/(_[a-z])/g,function(a){return a[1].toUpperCase()}):a},l=function(a,b,c){a.hasOwnProperty(b)||(a[b]=c)},m=function(a,e,f){var k={},m={},n={},p=pf("custom_map",a);if(pa(p))for(var q in p)if(p.hasOwnProperty(q)&&/^(dimension|metric)\d+$/.test(q)){var r=pf(p[q],a);void 0!==
r&&l(m,q,r)}for(var x=Ac(a,void 0),v=0;v<x.length;++v){var G=x[v],L=pf(G,a);d.hasOwnProperty(G)?h(d[G],G,L,k):c.hasOwnProperty(G)?h(c[G],G,L,m):b.hasOwnProperty(G)?h(b[G],G,L,n):/^(dimension|metric|content_group)\d+$/.test(G)&&h(1,G,L,m)}var H=String(ac);l(n,"cookieDomain","auto");l(m,"forceSSL",!0);var O="general";0<=ae("add_payment_info add_to_cart add_to_wishlist begin_checkout checkout_progress purchase refund remove_from_cart set_checkout_option".split(" "),H)?O="ecommerce":0<=ae("generate_lead login search select_content share sign_up view_item view_item_list view_promotion view_search_results".split(" "),
H)?O="engagement":"exception"==H&&(O="error");l(k,"eventCategory",O);0<=ae(["view_item","view_item_list","view_promotion","view_search_results"],H)&&l(m,"nonInteraction",!0);"login"==H||"sign_up"==H||"share"==H?l(k,"eventLabel",pf("method",a)):"search"==H||"view_search_results"==H?l(k,"eventLabel",pf("search_term",a)):"select_content"==H&&l(k,"eventLabel",pf("content_type",a));var R=k.linker||{};if(R.accept_incoming||0!=R.accept_incoming&&R.domains)n.allowLinker=!0;!1===pf("allow_display_features",
a)&&(m.displayFeaturesTask=null);n.name=e;m["&gtm"]=Be(!0);m.hitCallback=f;k.F=m;k.ub=n;return k},n=function(a){function b(a){var b=qa(a,void 0);b.list=a.list_name;b.listPosition=a.list_position;b.position=a.list_position||a.creative_slot;b.creative=a.creative_name;return b}function c(a){for(var c=[],d=0;a&&d<a.length;d++)a[d]&&c.push(b(a[d]));return c.length?c:void 0}function d(){return{id:e("transaction_id"),affiliation:e("affiliation"),revenue:e("value"),tax:e("tax"),shipping:e("shipping"),coupon:e("coupon"),
list:e("list_name")}}var e=function(b){return xc(b,a,void 0)},f=e("items"),h=e("custom_map");if(pa(h))for(var k=0;f&&k<f.length;++k){var m=f[k],n;for(n in h)h.hasOwnProperty(n)&&/^(dimension|metric)\d+$/.test(n)&&l(m,n,m[h[n]])}var p=null,q=ac,v=e("promotions");"purchase"==q||"refund"==q?p={action:q,aa:d(),X:c(f)}:"add_to_cart"==q?p={action:"add",X:c(f)}:"remove_from_cart"==q?p={action:"remove",X:c(f)}:"view_item"==q?p={action:"detail",aa:d(),X:c(f)}:"view_item_list"==q?p={action:"impressions",Zc:c(f)}:
"view_promotion"==q?p={action:"promo_view",Za:c(v)}:"select_content"==q&&v&&0<v.length?p={action:"promo_click",Za:c(v)}:"select_content"==q?p={action:"click",aa:{list:e("list_name")},X:c(f)}:"begin_checkout"==q||"checkout_progress"==q?p={action:"checkout",X:c(f),aa:{step:"begin_checkout"==q?1:e("checkout_step"),option:e("checkout_option")}}:"set_checkout_option"==q&&(p={action:"checkout_option",aa:{step:e("checkout_step"),option:e("checkout_option")}});p&&(p.Sd=e("currency"));return p},p={},q=function(a,
b){var c=p[a];p[a]=qa(b,void 0);if(!c)return!1;for(var d in b)if(b.hasOwnProperty(d)&&b[d]!==c[d])return!0;for(d in c)if(c.hasOwnProperty(d)&&c[d]!==b[d])return!0;return!1};(function(a){Z.__gtagua=a;Z.__gtagua.b="gtagua";Z.__gtagua.g=!0})(function(b){var c=b.vtp_trackingId,d=Qc(void 0),f="gtag_"+c.split("-").join("_"),p=function(a){var b=[].slice.call(arguments,0);b[0]=f+"."+b[0];d.apply(window,b)},v=function(){var a=function(a,b){for(var c=0;b&&c<b.length;c++)p(a,b[c])},b=n(c);if(b){var d=b.action;
if("impressions"==d)a("ec:addImpression",b.Zc);else if("promo_click"==d||"promo_view"==d){var e=b.Za;a("ec:addPromo",b.Za);e&&0<e.length&&"promo_click"==d&&p("ec:setAction",d)}else a("ec:addProduct",b.X),p("ec:setAction",d,b.aa)}},M=function(){var a=pf("optimize_id",c);a&&(p("require",a,{dataLayer:"dataLayer"}),p("require","render"))},C=m(c,f,b.vtp_gtmOnSuccess);q(f,C.ub)&&d(function(){Rc()&&Rc().remove(f)});d("create",c,C.ub);(function(){var a=pf("custom_map",c);d(function(){if(pa(a)){var b=
C.F,c=Rc().getByName(f),d;for(d in a)if(a.hasOwnProperty(d)&&/^(dimension|metric)\d+$/.test(d)){var e=c.get(k(a[d]));l(b,d,e)}}})})();(function(a){if(a){var b={};if(pa(a))for(var c in e)e.hasOwnProperty(c)&&h(e[c],c,a[c],b);p("require","linkid",b)}})(C.linkAttribution);var N=C.linker;N&&N.domains&&Sc(f+".",N.domains,!!N.use_anchor,!!N.decorate_forms);var I=function(a,b,c){c&&(b=""+b);C.F[a]=b},K=ac;"page_view"==K?(M(),p("send","pageview",C.F)):"gtag.config"==K?0!=C.sendPageView&&(M(),p("send","pageview",
C.F)):"screen_view"==K?p("send","screenview",C.F):"timing_complete"==K?(I("timingCategory",C.eventCategory,!0),I("timingVar",C.name,!0),I("timingValue",hc(C.value)),void 0!==C.eventLabel&&I("timingLabel",C.eventLabel,!0),p("send","timing",C.F)):"exception"==K?p("send","exception",C.F):(0<=ae("view_item_list select_content view_item add_to_cart remove_from_cart begin_checkout set_checkout_option purchase refund view_promotion checkout_progress".split(" "),K)&&(p("require","ec","ec.js"),v()),I("eventCategory",
C.eventCategory,!0),I("eventAction",C.eventAction||K,!0),void 0!==C.eventLabel&&I("eventLabel",C.eventLabel,!0),void 0!==C.value&&I("eventValue",hc(C.value)),p("send","event",C.F));a||(a=!0,Ve("https://www.google-analytics.com/analytics.js",function(){Rc().loaded||b.vtp_gtmOnFailure()},b.vtp_gtmOnFailure))})}();

var tf={macro:function(a){if(T.Ka.hasOwnProperty(a))return T.Ka[a]}};tf.dataLayer=wc;tf.onHtmlSuccess=T.tb(!0);tf.onHtmlFailure=T.tb(!1);tf.callback=function(a){bc.hasOwnProperty(a)&&ec(bc[a])&&bc[a]();delete bc[a]};tf.mc=function(){$b[Zb.A]=tf;cc=Z.a;Ob=Ob||T};
tf.$c=function(){$b=D.google_tag_manager=D.google_tag_manager||{};if($b[Zb.A]){var a=$b.zones;a&&a.unregisterChild(Zb.A)}else{for(var b=data.resource||{},c=b.macros||[],d=0;d<c.length;d++)Gb.push(c[d]);for(var e=b.tags||[],f=0;f<e.length;f++)Kb.push(e[f]);for(var h=b.predicates||[],k=0;k<h.length;k++)Jb.push(h[k]);for(var l=b.rules||[],m=0;m<l.length;m++){for(var n=l[m],p={},q=0;q<n.length;q++)p[n[q][0]]=Array.prototype.slice.call(n[q],1);Ib.push(p)}Mb=Z;Vd();tf.mc();Cd();Jc=!1;Kc=0;if("interactive"==
E.readyState&&!E.createEventObject||"complete"==E.readyState)Mc();else{Ia(E,"DOMContentLoaded",Mc);Ia(E,"readystatechange",Mc);if(E.createEventObject&&E.documentElement.doScroll){var v=!0;try{v=!D.frameElement}catch(x){}v&&Nc()}Ia(D,"load",Mc)}ud=!1;"complete"===E.readyState?wd():Ia(D,"load",wd);}};tf.$c();

})()
